name: build-release

on:
  push:
    branches: [main]

defaults:
  run:
    # GitHub Actions run without a TTY device. This is a workaround to get one,
    # based on https://github.com/actions/runner/issues/241#issuecomment-2019042651
    shell: 'script --return --quiet --log-out /dev/null --command "bash -e {0}"'
    
jobs:
  build-release:
    name: Build a binary release
    runs-on: ubuntu-24.04
    steps:
      - name: Clone code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/workflows/env
      - name: Build a builder docker image
        run: make docker-image
      - name: Build the agent binary
        run: make agent
      - name: Compute agent binary hash
        id: hash
        run: echo "::set-output name=binary_hash::$(sha256sum ebpf-profiler | cut -d ' ' -f 1)"
      - name: Short release tag hash
        id: taghash
        run: echo "::set-output name=tag_hash::$(echo ${{ steps.hash.outputs.binary_hash }} | cut -c -7)"
      - name: Create a github release
        uses: softprops/action-gh-release@v2
        with:
          files: ebpf-profiler
          tag_name: ${{ steps.taghash.outputs.tag_hash }}
          body: |
            The binary was built from commit ${{ github.sha }}.
            The SHA256 hash of the compiled binary is ${{ steps.hash.outputs.binary_hash }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
